performance_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('performance_reports.urls')),
]

performance_reports/urls.py
"""Define URL patterns for performance_reports"""

from django.urls import path
from . import views

app_name = 'performance_reports'

urlpatterns = [
    path('', views.index, name="index"),
    path('export-notes', views.export_notes, name="export-notes"),
    path('export-notes/get-str', views.get_random_string, name="get-str"),
    path('add-user', views.add_user, name="add-user"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('change-pwd', views.user_update_pwd, name="change-pwd"),
    path('user-admin', views.user_admin, name="user-admin"),
    path('admin-only', views.admin_only, name="admin-only"),
    path('user-admin/delete-user/<str:username>', views.user_admin_delete_user, name="delete-user"),
    path('user-admin/update-user', views.user_admin_update_user_pwd, name="update-user"),
]

performance_reports/models.py
from django.db import models

# Create your models here.

performance_reports/views.py
import io
from django.conf import settings
from django.urls import reverse
from urllib.parse import urlencode
from django.shortcuts import render, redirect
from django.db import Error
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
import json
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font

from modules.get_data import get_cases
from modules.excel_module import *
from modules.case_note_func import transform_case_note_data
from modules.export_case_notes import *
from modules.pd_user import *

# Create your views here.
@login_required
def index(request):
    try:
        #print(request.user.is_authenticated)
        return render(request, 'performance_reports/index.html')
    except Error as err:
        return HttpResponse(f"Error: {err}")

@login_required
def export_report(request):
    try:
        data_output = get_cases('1 Jan 2022', '23 mar 2022', '89,16,5,30', '')
        print(data_output)

        if request.method == "POST":

            excel_data = io.BytesIO()

            response = HttpResponse(excel_data, headers={
                'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 
                'Content_Disposition': 'attachment; filename="Test_file.xlsx"',})
            return response
        return render(request, 'performance_reports/reports.html')
    except Error as err:
        return HttpResponse(f"Error: {err}")

@login_required
def export_notes(request):
    try:
        if request.method == 'POST':

            clientID = request.POST['clientID']
            pw_str = request.POST['random-str']
            srv_str = ''
            grp_str = ''

            excel_data = create_case_notes(clientID, pw_str)

            response = HttpResponse(excel_data, headers={
                'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 
                'Content_Disposition': 'attachment; filename="Case_notes.xlsx"',})

            return response

        else:
            return render(request, 'performance_reports/export-notes.html')

    except Error as err:
        return HttpResponse(f"Error: {err}")

@login_required
def get_random_string(request):
    pw_str = create_random_pw_string()
    return HttpResponse(pw_str)

@login_required
def add_user(request):
    user_message = {'message': ''}
    if request.method == 'POST':
        username = request.POST['username']
        pwd_str = request.POST['pwd']
        pwd_confirm_str = request.POST['pwd-confirm']

        if pwd_str == pwd_confirm_str:
            add_user_result = add_pd_user(username, pwd_str)
            user_message['message'] = add_user_result
        else:
            user_message['message'] = 'Passwords did not match'
            user_message['username'] = username

    return render(request, 'performance_reports/add-user.html', user_message)

def admin_check(user):
    # check if user is admin
    username = user.username
    admin_check = check_user_is_admin(username)
    return admin_check

def user_login(request):
    user_message = {'message': ''}
    try:
        if request.method == 'POST':
            username = request.POST['username']
            pwd = request.POST['pwd']
            user = authenticate(request, username=username, password=pwd)

            if user is not None:
                login(request, user)
                record_login_time(username)
                admin_check_result = admin_check(user)
                if admin_check_result:
                    request.session['user_type'] = 1
                return redirect('/')
            else:
                user_message['message'] = 'Invalid login'
        return render(request, 'performance_reports/login.html', user_message)

    except Error as err:
        return HttpResponse(f"Error: {err}")

def user_logout(request):
    logout(request)
    return redirect('/')



@user_passes_test(admin_check, login_url='/admin-only')
def user_admin(request):
    try:
        user_dict = get_all_users()
        return render(request, 'performance_reports/user-admin.html', user_dict)
    except Error as err:
        return HttpResponse(f"Error: {err}")

@user_passes_test(admin_check, login_url='/admin-only')
def user_admin_delete_user(request, username):
    try:
        delete_user(username)
        return redirect('performance_reports:user-admin')
    except Error as err:
        return HttpResponse(f"Error: {err}")

@user_passes_test(admin_check, login_url='/admin-only')
def user_admin_update_user_pwd(request):
    try:
        if request.method == 'POST':
            username = request.POST['username']
            user_id = request.POST['user-id']
            pwd_str = request.POST['pwd']
            pwd_confirm_str = request.POST['pwd-confirm']

            if pwd_str == pwd_confirm_str:
                update_result = update_user_pwd(username, pwd_str)
                print(update_result)
                return redirect('performance_reports:user-admin')
            else:
                base_url = reverse('performance_reports:user-admin')
                query_str = urlencode({'user-id': user_id})
                url = f'{base_url}?{query_str}'
                return redirect(url)

    except Error as err:
        return HttpResponse(f"Error: {err}")

@login_required
def admin_only(request):
    try:
        return render(request, 'performance_reports/admin-only.html')
    except Error as err:
        return HttpResponse(f"Error: {err}")

@login_required
def user_update_pwd(request):
    user_message = {'message': ''}
    try:
        if request.method == 'POST':
            username = request.POST['username']
            current_pwd_str = request.POST['pwd-current']
            pwd_str = request.POST['pwd']
            pwd_confirm_str = request.POST['pwd-confirm']
            user = authenticate(request, username=username, password=current_pwd_str)

            if user and username == user.username:
                if pwd_str == pwd_confirm_str:
                    update_result = update_user_pwd(username, pwd_str)
                    # log out then redirect to login
                    logout(request)
                    base_url = reverse('performance_reports:login')
                    query_str = urlencode({'user_updated': 'True'})
                    url = f'{base_url}?{query_str}'
                    return redirect(url)
                else:
                    user_message['message'] = 'Passwords do not match'
            else:
                user_message['message'] = 'Could not verify user'
        return render(request, 'performance_reports/change-pwd.html', user_message)

    except Error as err:
        return HttpResponse(f"Error: {err}")

performance_reports/templates/performance_reports/add-user.html
{% extends "performance_reports/base.html" %}
{% block content %}
<p>Add new user</p>
<form action="/add-user" method="POST">
    {% csrf_token %}
    <div class="row p-3">
        <div class="col-3">
            <div class="row p-1">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username" value="{{username}}" />
            </div>
            <div class="row p-1">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="pwd" name="pwd" />
            </div>
            <div class="row p-1">
                <label for="password" class="form-label">Confirm password</label>
                <input type="password" class="form-control" id="pwd-confirm" name="pwd-confirm" />
            </div>
            <div class="row p-1">
                <label for="user-type">User type</label>
                <select class="form-select" id="user-type" name="user-type">
                    <option selected value="2">User</option>
                    <option value="1">Administrator</option>
                </select>
            </div>
        </div>
        <div class="col d-flex align-items-end">
            <button type="submit" class="btn btn-outline-light text-white">Add user</button>
        </div>
    </div>
    <div class="row p-3">
        <p style="font-style: italic">{{message}}</p>
    </div>

</form>

{% endblock content %}

performance_reports/templates/performance_reports/add_user.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <title>Performance Dashboard</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">


</head>
<body>
    <div class="container p-3 h-25 my-5 bg-dark text-white">
        <h1>Performance reports</h1>
        <p>Add new user</p>
        <form action="/add_user" method="POST">
            {% csrf_token %}
            <div class="row p-3">
                <div class="col-3">
                    <div class="row p-1">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username" />
                    </div>
                    <div class="row p-1">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="pwd" name="pwd" />
                    </div>
                    <div class="row p-1">
                        <label for="password" class="form-label">Confirm password</label>
                        <input type="password" class="form-control"/>
                    </div>
                </div>
                <div class="col d-flex align-items-end">
                    <button type="submit" class="btn btn-outline-light text-white">Add user</button>
                </div>
            </div>
            <div class="row p-3">
                <p style="font-style: italic">{{message}}</p>
            </div>

        </form>
    </div>

    <script>
        "use strict";
        function checkSpecialChar(event) {
            var e = document.getElementById('myInput');
            var chr = e.value
            if (chr.match(/[^a-zA-Z0-9\s]/g))
                event.preventDefault();
                //return false;
        };
        let searchBox = document.getElementById('myInput');
        searchBox.addEventListener('keypress', checkSpecialChar, false)

        let textInput = searchBox.value

        if (textInput) {
            searchFunction()
        }

        function searchFunction() {
            // Declare variables
            var input, filter, ul, li, a, i, txtValue;
            input = document.getElementById('myInput');
            filter = input.value.toUpperCase();
            ul = document.getElementById("service-list");
            li = ul.getElementsByTagName('li');

            // Loop through all list items, and hide those who don't match the search query
            for (i = 0; i < li.length; i++) {
                a = li[i].getElementsByTagName("a")[0];
                txtValue = a.textContent || a.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    li[i].style.display = "";
                } else {
                    li[i].style.display = "none";
                }
            }
        }

        function checkToggle(serviceNo) {
            var checkbox = document.getElementById("service" + serviceNo + "checkbox");
            if (checkbox.checked == true) {
                checkbox.checked = false;
                } else {
                    checkbox.checked = true;
                }
        }
        // convert posted services to JS array
        const srvFormData = "{{service_ID}}";
        if (srvFormData) {
            let matched_no = srvFormData.match(/[0-9]+/g);
            let service_arr = [];
            matched_no.forEach(element => {
                let srvID = parseInt(element);
                service_arr.push(srvID)
            });
        }

        function checkRemember(serviceNo) {
            var checkbox = document.getElementById("service" + serviceNo + "checkbox");
            checkbox.checked = true;
        }
    </script>

</body>
</html>

performance_reports/templates/performance_reports/admin-only.html
{% extends "performance_reports/base.html" %}
{% block content %}

<div>
    <p>Restricted - administrators only</p>
    <a href="{% url 'performance_reports:index' %}" class="btn btn-secondary">Return to homepage</a>
</div>

{% endblock content %}

performance_reports/templates/performance_reports/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <title>Performance Dashboard</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'performance_reports/style.css' %}">

</head>
<body>
    <div class="container p-3 h-100 my-5 bg-dark text-white">
        {% if user.is_authenticated %}
        <div class="row" id="nav-links">Logged in as: <b>{{user.username}}</b></div>
        {% endif %}
        <div class="row" id="nav-links">
            <a href="{% url 'performance_reports:index' %}">Home</a> <a href="{% url 'performance_reports:export-notes' %}">Export case notes</a>
            {% if request.session.user_type == 1 %}
                <a href="{% url 'performance_reports:user-admin'%}">Manage users</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a href="{% url 'performance_reports:change-pwd'%}">Change password</a>
            <a href="{% url 'performance_reports:logout'%}">Log out</a>
            {% endif %}
        </div>

        <div class="row" name="header-div-row" id="header-div-row">
                <h1>Performance dashboard</h1>
        </div>

        {% block content %}{% endblock content %}

    </div>


</body>
</html>

performance_reports/templates/performance_reports/change-pwd.html
{% extends "performance_reports/base.html" %}
{% block content %}
<p>Change your password</p>
<form action="/change-pwd" method="POST">
    {% csrf_token %}
    <div class="row p-3">
        <div class="col-3">

                <input type="hidden" class="form-control" id="username" name="username" value="{{user.username}}" />

            <div class="row p-1">
                <label for="password" class="form-label">Current password</label>
                <input type="password" class="form-control" id="pwd-current" name="pwd-current" />
            </div>
            <div class="row p-1">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="pwd" name="pwd" />
            </div>
            <div class="row p-1">
                <label for="password" class="form-label">Confirm password</label>
                <input type="password" class="form-control" id="pwd-confirm" name="pwd-confirm" />
            </div>

        </div>
        <div class="col d-flex align-items-end">
            <button type="submit" class="btn btn-outline-light text-white">Change password</button>
        </div>
    </div>
    <div class="row p-3">
        <p style="font-style: italic; color: orange;">{{message}}</p>
    </div>

</form>

{% endblock content %}

performance_reports/templates/performance_reports/export-notes.html
{% extends "performance_reports/base.html" %}
{% block content %}

<p>Export case notes</p>
<p style="font-style: italic">Please verify case notes are for correct client</p>
<form action="/export-notes" method="POST" id="search-form">
    {% csrf_token %}
    <div class="row p-3">
        <div class="col">
            <label for="clientID" class="form-label">Enter client ID:</label>
            <input type="number" class="form-control" id="clientID" name="clientID" />
            <input type="hidden" id="random-str" name="random-str" value="" />
        </div>

        <div class="col d-flex align-items-end">
            <button type="submit" id="submit-button" class="btn btn-outline-light text-dark"><i class="bi bi-search" style="color: white;"> Search</i></button>
        </div>

    </div>
    <div class="row p-3">
        <div class="col-6" id="status-box" name="status-box" style="display: none">
        </div>
    </div>

</form>


<script>
    "use strict";
    const statusBox = document.getElementById('status-box');
    const randomStrFormField = document.getElementById('random-str');
    const submitButton = document.getElementById('submit-button');
    var randStr;

    function getRandomString() {
        fetch('/export-notes/get-str')
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error: ${response.status}`);
                }
                return response.text()
            })
            .then(random_str => {
                randStr = random_str;
                randomStrFormField.value = random_str;
                //console.log(random_str);
            })
            .catch(err => console.error(`${err.message}`));
    }

    function displayRandomStr() {
        statusBox.innerHTML = '<p>' + randStr + '</p>';
        statusBox.style.display = "block";
    }

    function updateRandomStr() {
        // display existing random str
        displayRandomStr();
        // load new random str for next submit
        getRandomString()
    }

    window.addEventListener('load', getRandomString);
    submitButton.addEventListener('click', updateRandomStr);

    /*
    function checkSpecialChar(event) {
        var e = document.getElementById('myInput');
        var chr = e.value
        if (chr.match(/[^a-zA-Z0-9\s]/g))
            event.preventDefault();
            //return false;
    };
    */

</script>

{% endblock content %}

performance_reports/templates/performance_reports/export_notes.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <title>Performance Dashboard</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'performance_reports/style.css' %}">

</head>

<body>
    <div class="container p-3 h-25 my-5 bg-dark text-white">
        <h1>Performance reports</h1>
        <p>Export case notes</p>
        <p style="font-style: italic">Please verify case notes are for correct client</p>
        <form action="/export_notes" method="POST" id="search-form">
            {% csrf_token %}
            <div class="row p-3">
                <div class="col">
                    <label for="clientID" class="form-label">Enter client ID:</label>
                    <input type="number" class="form-control" id="clientID" name="clientID" />
                    <input type="hidden" id="random-str" name="random-str" value="" />
                </div>

                <div class="col d-flex align-items-end">
                    <button type="submit" id="submit-button" class="btn btn-outline-light text-dark"><i class="bi bi-search" style="color: white;"> Search</i></button>
                </div>

            </div>
            <div class="row p-3">
                <div class="col-6" id="status-box" name="status-box" style="display: none">
                </div>
            </div>

        </form>
    </div>

    <script>
        "use strict";
        const statusBox = document.getElementById('status-box');
        const randomStrFormField = document.getElementById('random-str');
        const submitButton = document.getElementById('submit-button');
        var randStr;

        function getRandomString() {
            fetch('/export_notes/get_str')
                .then(response => {
                    if (!response.ok) {
                        throw new Error(`HTTP error: ${response.status}`);
                    }
                    return response.text()
                })
                .then(random_str => {
                    randStr = random_str;
                    randomStrFormField.value = random_str;
                    //console.log(random_str);
                })
                .catch(err => console.error(`${err.message}`));
        }

        function loadRandomStr() {
            statusBox.innerHTML = '<p>' + randStr + '</p>';
            statusBox.style.display = "block";
        }

        function updateRandomStr() {
            // expose existing random str
            loadRandomStr();
            // load new random str for next submit
            getRandomString()
        }

        window.addEventListener('load', getRandomString);
        submitButton.addEventListener('click', updateRandomStr);

        function checkSpecialChar(event) {
            var e = document.getElementById('myInput');
            var chr = e.value
            if (chr.match(/[^a-zA-Z0-9\s]/g))
                event.preventDefault();
                //return false;
        };

    </script>

</body>
</html>

performance_reports/templates/performance_reports/index.html
{% extends "performance_reports/base.html" %}
{% block content %}


<div class="row">
    <div class="col">
        <p>Welcome to performance dashboard</p>
    </div>
</div>
<div>
    <a href="{% url 'performance_reports:export-notes' %}" class="btn btn-secondary btn-lg"><i class="bi bi-person-rolodex"></i> Export client case notes</a>
    <a href="#" class="btn btn-secondary btn-lg"><i class="bi bi-clipboard-data"></i> Export stats report</a>
    {% if request.session.user_type == 1 %}
    <a href="{% url 'performance_reports:user-admin' %}" class="btn btn-secondary btn-lg"><i class="bi bi-people-fill"></i> Manage performance dashboard users</a>
    {% endif %}
</div>

{% endblock content %}

performance_reports/templates/performance_reports/logout.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <title>Performance Dashboard</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">


</head>
<body>
    <div class="container p-3 h-25 my-5 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h1>Performance reports</h1>
                <p>Logged out succesfully</p>
            </div>
        </div>

    </div>


</body>
</html>

performance_reports/templates/performance_reports/user-admin.html
{% extends "performance_reports/base.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <p>Manage performance dashboard users</p>
    </div>
    <div class="col" style="text-align:right;">
        <a href="{% url 'performance_reports:add-user' %}" class="bi bi-person-plus-fill btn btn-secondary">Add new user</a>
    </div>
</div>

    <div class="row">
        <p>{{user_message}}</p>
    </div>

    <div class="row bg-light">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>User type</th>
                    <th>Last login</th>
                    <th>Admin</th>
                </tr>
            </thead>
            <tbody>
                {% for user in user_rows %}
                <tr>
                    <td>{{user.1}}</td>
                    <td>{{user.2}}</td>
                    <td>{{user.3}}</td>
                    <td>
                        <button class="bi bi-trash-fill btn btn-outline-secondary btn-sm" id="delete-btn-userID{{user.0}}" value="{{user.0}}">Delete</button>
                        <button class="bi bi-pencil-square btn btn-outline-secondary btn-sm" id="change-pwd-btn-userID{{user.0}}" value="{{user.0}}">Change password</button>

                        <div class="alert alert-warning delete-confirm-box" style="display:none;" id="delete-status-userID{{user.0}}">
                            Are you sure you want to delete user: <b>{{user.1}}</b>? <br>
                            <a class="bi bi-check-lg btn btn-light btn-sm" href="/user-admin/delete-user/{{user.1}}">Yes</a>
                            <button class="bi bi-x-lg btn btn-light btn-sm" id="delete-cancel-userID{{user.0}}" value="{{user.0}}">No</button>
                        </div>

                        <div class="alert alert-dark change-pwd-box" style="display:none;" role="alert" id="change-pwd-box-userID{{user.0}}">
                            <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                            Change password for user: <b>{{user.1}}</b>
                            <form action="user-admin/update-user" method="POST" style="padding:9px;">
                                {% csrf_token %}
                                <div>
                                    <input type="hidden" class="form-control-sm" id="userID{{user.0}}" name="user-id" value="{{user.0}}" />
                                    <input type="hidden" class="form-control-sm" id="username{{user.0}}" name="username" value="{{user.1}}" />

                                    <div class="row mb-2">
                                        <label for="password" class="col-sm-3 form-label">New password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control-sm" id="pwd{{user.0}}" name="pwd" />
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <label for="password" class="col-sm-3 form-label">Confirm password</label>
                                        <div class="col-sm-9">
                                            <input type="password" class="form-control-sm" id="pwd-confirm{{user.0}}" name="pwd-confirm" />
                                        </div>
                                    </div>
                                    <div>
                                        <button type="submit" class="btn btn-dark btn-sm text-white">Change password</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>

    </div>

    <script>
        "use strict";
        let delBtns = document.querySelectorAll('button.bi-trash-fill');
        let hideDeleteBtns = document.querySelectorAll('button.bi-x-lg');
        let changePwdBtns = document.querySelectorAll('button.bi-pencil-square');

        delBtns.forEach(item => {
            item.addEventListener('click', function () { handleDelete(item.value); });
        })

        hideDeleteBtns.forEach(item => {
            item.addEventListener('click', function () { hideDeleteConfirm(item.value); });
        })

        changePwdBtns.forEach(item => {
            item.addEventListener('click', function () { showPwdChangeBox(item.value); });
        })

        function getStatusBoxByUserId(statusBoxId, userId) {
            let statusBoxName = `${statusBoxId}${userId}`;
            let statusBox = document.querySelector(statusBoxName);
            return statusBox
        }

        function handleDelete(userId) {
            let deleteConfirmBox = getStatusBoxByUserId('#delete-status-userID', userId);
            deleteConfirmBox.style.display = 'inline-block';
        }

        function hideDeleteConfirm(userId) {
            let deleteConfirmBox = getStatusBoxByUserId('#delete-status-userID', userId);
            deleteConfirmBox.style.display = 'none';
        }

        function showPwdChangeBox(userId) {
            let pwdChangeBox = getStatusBoxByUserId('#change-pwd-box-userID', userId);
            pwdChangeBox.style.display = 'inline-block';
        }

        const parsedURL = new URL(window.location.href);
        let userId = parsedURL.searchParams.get("user-id");
        if (userId) {
            let pwdChangeBox = getStatusBoxByUserId('#change-pwd-box-userID', userId);
            if (pwdChangeBox) {
                pwdChangeBox.innerHTML = pwdChangeBox.innerHTML + '<div class="alert alert-danger" role="alert">Passwords did not match</div>';
                showPwdChangeBox(userId);
            }
        }

    </script>

    {% endblock content %}